# NumPy Arrays

## NumPy is a Python library used for working with arrays. 
## NumPy stands for `Numerical Python.`

## <blockquote>Why use NumPy?</blockquote>
#### NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

#### The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy.

In [2]:
import numpy as np

# a normal list
mylist = [1, 2, 3, 4, 5]

# a list with numpy
arr = np.array([1, 2, 3, 4, 5])

print(mylist, arr)
print(f'Normal list type: {type(mylist)}\nNumpy array type: {type(arr)}')

[1, 2, 3, 4, 5] [1 2 3 4 5]
Normal list type: <class 'list'>
Numpy array type: <class 'numpy.ndarray'>


## <blockquote>Transforming normal lists into NumPy Arrays</blockquote>

In [4]:
mylist = [1, 2, 3, 4, 5]
print(mylist)
myarr = np.array(mylist)
print(myarr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


## <blockquote>Dimensions in Arrays</blockquote>
## `0-D Arrays`

In [5]:
arr = np.array(61)
print(arr)                              # 61 here is a zero-dimensional array

61


numpy.ndarray

## `1-D Arrays`

In [6]:
arr = np.array([5, 10, 15, 20])
print(arr)                             # a uni-dimensional array consisting of 0-D arrays

[ 5 10 15 20]


## `2-D Arrays`

In [7]:
matrix = np.array([[1, 3, 5], [2, 4, 6]])
print(matrix)                          # a 2-D array containing two 1-D arrays

[[1 3 5]
 [2 4 6]]


## `3-D Arrays`

In [8]:
matrix = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(matrix)                          # a 3-D array containing two 2-D arrays

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## `Higher Dimensional Arrays`
### When an array is created, you can define the number of dimensions by using the `ndmin` argument.

In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


## <blockquote>Checking the number of Dimensions</blockquote>

### NumPy Arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have.

In [10]:
# array.ndim

zero = np.array(61)
one = np.array([5, 10, 15, 20])
two = np.array([[1, 3, 5], [2, 4, 6]])
three = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# using ndim to find out dimensions
print(one.ndim)
print(three.ndim)

1
3


## <blockquote>Built-in Functions</blockquote>

## `arange`
### Returns evenly spaced values within a given interval.

In [12]:
# np.arange(start, stop, stepsize) 

arr = np.arange(0, 101, 10)   # stopping point not included
print(arr)

[  0  10  20  30  40  50  60  70  80  90 100]


## `linspace`
### Returns evenly spaced numbers over a specified interval.

In [18]:
# np.linspace(start, stop, num)

arr = np.linspace(0, 10, 20)  # stopping point included
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


## `zeros`
### Returns a new array of given shape and type, filled with zeros.

In [13]:
# np.zeros(shape)

# one dimensional
arr = np.zeros(5)
print(f'1-D Array: {arr}')

# 2-D array
arr = np.zeros((4, 6))
print(f'\nMatrix with floating point numbers:\n {arr}')

# with int
arr = np.zeros((4, 6), dtype=int)
print(f'\nMatrix with integers:\n {arr}')

# 3-D Array
arr = np.zeros((4, 3, 7))
print(f'\n 3-D Array:\n {arr}')

1-D Array: [0. 0. 0. 0. 0.]

Matrix with floating point numbers:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Matrix with integers:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 3-D Array:
 [[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


## `ones`
### Returns a new array of given shape and type, filled with ones.

In [14]:
# np.ones(shape)

arr = np.ones((2, 5), dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]]


## `eye`
### Creates an identity matrix, ones on the diagonal and zeros elsewhere.

In [22]:
# np.eye(number)

arr = np.eye(4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## `dtype`
### Returns the data type of the array.

In [34]:
# arr.dtype

arr1 = np.array([[1, 3, 5], [2, 4, 6]])
arr2 = np.array([[[1, 2, 3.5], [4, 5.2, 6]]])
arr3 = np.array(['apple', 'banana', 'cake'])       # 6 in U6 shows the length of the longest string in array

print(f'First array data type: {arr1.dtype}')
print(f'Second array data type: {arr2.dtype}')
print(f'Third array data type: {arr3.dtype}')

First array data type: int32
Second array data type: float64
Third array data type: <U6


## `astype`
### Copies the array and converts it into a specified type.

In [42]:
# arr.astype(dtype)

arr = np.array([10.5, 20.1, 30.4, 40.6, 50.3])
print(f'Given array: {arr}')

int_arr = arr.astype('int32')
print(f'Integer array: {int_arr}')

Given array: [10.5 20.1 30.4 40.6 50.3]
Integer array: [10 20 30 40 50]


## <blockquote>Generating random data</blockquote>

## `rand`
### Returns an array of a given shape consisting of floats between 0 and 1.

In [16]:
# np.random.rand(d0, d1, ... dn)

arr = np.random.rand(3)
print(f'1-D random Array: {arr}\n')

arr = np.random.rand(2, 3, 4)
print(f'3-D random Array:\n {arr}')

1-D random Array: [0.9979028  0.4522831  0.27189378]

3-D random Array:
 [[[0.96418501 0.17443003 0.69752974 0.04145537]
  [0.96419444 0.33343172 0.8627363  0.03330403]
  [0.72996931 0.22868009 0.03980126 0.88395047]]

 [[0.47955247 0.32305718 0.84576313 0.79450248]
  [0.36925791 0.95313148 0.92943191 0.1546979 ]
  [0.11994141 0.58985785 0.02168362 0.18362571]]]


## `randn`
### Returns a sample (or samples) from the “standard normal” distribution.

In [17]:
# np.random.randn(d0, d1, ... dn)

arr = np.random.randn(2, 3)
print(arr)

[[ 1.21597972 -0.06408164  0.25463151]
 [-2.01996944 -0.4163979  -0.24152076]]


## `randint`
### Return random integers from *low* (inclusive) to *high* (exclusive).

In [18]:
# np.random.randint(low, high, num/shape)

arr = np.random.randint(1, 15, 4)
print(f'Four random integers between 1 and 15:\n{arr}')

matrix = np.random.randint(1, 15, (2, 4))
print(f'\n2-D array containing integers between 1 and 15:\n{matrix}')

Four random integers between 1 and 15:
[ 6  9  7 11]

2-D array containing integers between 1 and 15:
[[ 8 11 13 10]
 [ 2 11  4  1]]


## `seed`
### NumPy allows you to set an arbitrary seed number to get a particular set of random numbers.

In [85]:
# np.random.seed(num)

np.random.seed(42)
arr = np.random.rand(4)
print(arr)                                  # like a sequence

[0.37454012 0.95071431 0.73199394 0.59865848]


## <blockquote>Shaping / Reshaping</blockquote>

## `shape`
### Returns the number of elements in each dimension (referred as the "shape" of array)

In [29]:
# get the shape of an array
# array.shape

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f'Shape of the first array: {arr1.shape}')
print(f'Shape of the second array: {arr2.shape}')
print(f'Shape of the third array: {arr3.shape}')

Shape of the first array: (5,)
Shape of the second array: (2, 3)
Shape of the third array: (2, 2, 3)


## `reshape`
### Changes the shape of array without altering the data

## `1D-2D Reshaping`

In [46]:
# change the shape of an array
# numpy.reshape(array, shape)

arr = np.array([1, 3, 5, 7, 9, 11])

np.reshape(arr, (2, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11]])

## `1D-3D Reshaping`

In [47]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

np.reshape(arr, (2, 3, 2))

array([[[ 2,  4],
        [ 6,  8],
        [10, 12]],

       [[14, 16],
        [18, 20],
        [22, 24]]])

## It is not possible to reshape into any shape:

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# np.reshape(arr, (2, 5)) # it will give an error 

## `max`
### Returns the maximum value in an array

In [49]:
# get the maximum value in array
# array.max()

arr = np.array([32, 78, 39, 78, 93, 1, 2])

arr.max()

93

## `min`
### Returns the minimum value in an array

In [50]:
# get the minimum value in array
# array.min()

arr = np.array([23, 71, 389, 389, -3, 1, 2])

arr.min()

-3

## `argmax`
### Returns the index of the maximum value in an array

In [51]:
# get the index of the maximum value in array
# array.argmax()

arr = np.array([32, 78, 39, 77, 93, 1, 2])

arr.argmax()

4

## `argmin`
### Returns the index of the minimum value in an array

In [52]:
# get the index of the  minimum value in array
# array.argmin()

arr = np.array([23, 71, 389, 389, -3, 1, 2])

arr.argmin()

4

## <blockquote> Exercises </blockquote> 

### `Exercise 1:` Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive).

In [67]:
# Solution Here

### `Exercise 2:` Convert the 1-D array into a 3-D array.

In [66]:
arr = np.linspace(1, 27, 27, dtype=int)

# Solution Here

### `Exercise 3:` Create different shapes of the same sequence of  integers using random library.

In [95]:
# Solution Here